name: Build Stravaig.Extensions.Logging.Diagnostics
on: 
  push:
    branches: 
      - main

jobs:
  build:
    name: Stravaig Test Capture Logger
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        name: Setup .NET Core
        with:
          dotnet-version: 3.1.402
          source-url: https://nuget.pkg.github.com/<organization>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build Solution
        run: dotnet build src/Stravaig.Extensions.Logging.Diagnostics.sln --configuration Release
        
      - name: Run Tests
        run: dotnet test src/Stravaig.Extensions.Logging.Diagnostics.Tests/Stravaig.Extensions.Logging.Diagnostics.Tests.csproj --configuration Release
        
      - name: Package Project
        run: dotnet pack ./src/Stravaig.Extensions.Logging.Diagnostics/Stravaig.Extensions.Logging.Diagnostics.csproj --configuration Release --output ./out --include-symbols --include-source /p:VersionPrefix="0.0.1" --version-suffix "preview-$GITHUB_RUN_ID"
        
      - name: Push package to GitHub
        run: dotnet nuget push ./out/*.nupkg
        
